#+TITLE:  Studium Engine
#+AUTHOR: Lucas Vieira
#+EMAIL:  lucasvieira@lisp.com.br

* Introduction
Studium is a 2D game engine written in C from scratch. The main focus
is on portability and simplicity, while striving to follow good design
patterns.

* Implementation
** Unit testing
Uses [[https://libcheck.github.io/check/][libcheck]].
** Matrix and Vector operations
Based upon the book "Real Time Collision Detection", by Christer Ericson.

* License

This software is distributed under the GNU Lesser General Public License v3.0,
except for third-party software described below.

** Third-party

- =stb_image.h=
  Built by Sean T. Barrett. License is Public Domain.

- =glad.h=
  OpenGL loader interface, created using [[https://github.com/Dav1dde/glad][glad]]. License is Public Domain.

- =khrplatform.h=
  Khronos Group platform-specific types and definitions, fetched by [[https://github.com/Dav1dde/glad][glad]].
  License is MIT.

- =GLFW=
  Used for all things related to input/output, windowing, context creation.
  An awesome library distributed under the zlib license. Studium statically
  links GLFW onto its own dynamic library, but please be wary that note of
  this code is libstudium's!
